### PR TITLE
Add more punk styles, some horror styles, and some glitch styles

### PR DESCRIPTION
**Pull request by Efreak**
*Almost* all of these are purely Lora based

1. More stylepunks
- lunarpunk
- celtpunk
- toxicpunk
- mongolpunk
- musketpunk
- absinthepunk
- cattlepunk
- circuspunk
- aetherpunk
- potatopunk
- ivorygoldai

2. Horrors
- bodyhorror
- gothichorrorai
- tentaclehorrorai
- horrorpunk (existed, added to new category)
- dreadhorror
- reelhorror
- nastyhorrors (combination of body horror, reelhorror)
- sdxlhorror

3. Glitch art styles
- glitchart
- oldvhs
- analogdistortion
- pixelsorting

4. sdxl styles (no loras)
- sdxlcatgirlportrait
- sdxlstreetfashion
- sdxlhorror

### CODE REVIEW

**Comment by db0** [comment]
I believe I already have the manyeyedhorrorai as a stylepunk in "horrorpunk"

**Comment by Efreak** [comment]
Fixed. The reason this is only a draft is 

1. I need to double-check the Lora triggers, some of them might be wrong.
2. I've got a big list of all the *AI and \*Punk\* loras on Civitai and want to check which ones by *other* authors are worthwhile.

It also might be worthwhile adding detail enhancer Lora to some of these at ~0.3 strength, but I'm not sure how to do this.

**Comment by Efreak** [comment]
3e590eabdf7ed81b246170a8690062ec4242d9d2 changed from including triggers I'm unsure of to just using inject_trigger=any; according to line 318 of hordelib. py, setting it this way puts the first keyword at the beginning of the prompt.

Assuming the bot supports this, the PR is complete.

Some suggestions for hordelib:

if the inject_trigger=any, don't just pick the first keyword--pick one at random
if the inject_trigger=all, inject **all* triggers

suggestions for styles specifically:

It would also be nice if the triggers to inject could be an array rather than a string, so it could pick a keyword at random when submitting; the above suggestion takes care of loras, but not all triggers are loras, and not all styles even use loras. This would allow things like : `a portrait of a [human, elf, orc, barbarian]` with [RuneMagic](https://civitai.com/models/66359)

On that note, ay of the following could also make the bot more entertaining:
- config item to pick a random lora from the list (current all vs any)
- allow use of categories in the bot. when someone uses a category as a style it picks a style from that category randomly for each generation
  - I've suggested this to Zelda_Fan

**Comment by db0** [comment]
I generally avoid using trigger injection on styles, as I know exactly what I need, so I can just choose the trigger. But we can give it a try and see how it works,

> It would also be nice if the triggers to inject could be an array rather than a string, so it could pick a keyword at random when submitting; the above suggestion takes care of loras, but not all triggers are loras, and not all styles even use loras. This would allow things like : a portrait of a [human, elf, orc, barbarian] with [RuneMagic](https://civitai.com/models/66359)

This is not the purpose of the trigger injection through. It was mostly so that people don't have to exactly remember every trigger they use. To do this randomness you want, it's far better to create multiple styles and group them in a category which will handle this randomization.

For enhancing the trigger inject mechanism, please open an issue for the hordelib repo.

For enhancing the bot to use categories you need to talk to zelda_fan as you know. This is already handled on mastodon and reddit.

Selecting a random lora is not possible due to the sheer amount of loras, unless CivitAI itself provides a way to get a random model from their API.

**Pull request merged**
