### PR TITLE
Added new styles

### PR DESCRIPTION
**Pull request by rbrtcs1**
Rainbow, line art, charcoal drawing, pencil drawing, vintage photo

### CODE REVIEW

**Comment by db0** [comment]
I generally like to start making our styles to be a bit more elaborate than what one can come up in a couple seconds themselves. Like more advanced prompt crafting, using LoRas and TIs etc.

**Comment by rbrtcs1** [comment]
Totally understandable - efreak told me to PR the new ones I had on aiscribbles, but feel free to do whatever with them

**Comment by Efreak** [comment]
The rainbow style in particular is pretty good, and easily modified to add more to the looks with artist names and weights (I played around with it quite a bit in #bot). Despite being simple, it works quite well.

Vintage photo is simple, but works surprisingly well--I assumed it took more than that (admittedly, I haven't actually tried). There's a Polaroid Lora on Civitai now that might help with framing it as a Polaroid, I think, though idk how big it is.

Line art should be compared to the existing line art style, I would guess that @rbrtcs1 didn't notice this one.

Pencil drawing can possibly be used to make the existing (not very good) pencilscribbles style better. Pencilscribbles was supposed to be sketch/amateur, but there's some overlap.

Charcoal drawing could probably be enhanced as well to include texture (also remove sharp focus--that's probably part of what's making it look too realistic).

Caricature actually looks pretty good. Someone was showing off caricatures Lora on stable foundation, and this doesn't seem far off.

------

As far as official styles go, I've got the separate file for things that aren't in the bot; we can add more styles there, and move them into the bot for parties and the like on request. The file structure there is different, 

Playing cards, mtg card, baseball card, greeting card and some other simplistic styles can be removed to make room for these -- they never worked very well, and I had intended to make those styles better eventually, but never got around to it.

Styles that need testing (they were needed with SDXL base, unknown if they're still needed with Albedo and other finetunes) include building, claymation.

Styles that don't seem to work as well without refiner (they worked with the beta) include animation.

Simplistic styles that can probably be removed entirely include Disney and Pixar, fustercluck (I planned to replace it with fustercluck 3d style, which enhances it)

Some of the original styles can probably be removed to the secondary list as well; I've been avoiding touching the styles that predate my involvement, but I can do so if requested.
- Comic diffusion and other model-based styles can probably be replaced by adding the model list itself to the bot (have the bot load the list of models, set params from baseline, then have any defined styles with the same name overwrite those). The bot can then use the triggers list defined in the model reference, picking one at random for each generation.
- Stylepunks have mostly lost popularity as well, and the most popular (steampunk, cyberpunk, etc) don't need loras at all with SDXL. Keep the most popular ones, and leave the rest in a list of "good" flexible loras somewhere (separate from the worker's curated loras list). 

It might be worthwhile to add tags to the styles list in addition to categories. Tags could include things like __official Horde style__ (eg the bot can filter to these), __community style__, __Lora/embedding__ (for styles based only on a Lora/TI), __prompt template__ (for styles with only a template), and things like anime realistic etc that the categories list already uses.
- I tried having the same styles in multiple categories previously, but IIRC multiple UIs didn't load properly with this. Calling it tags instead should fix this, and putting them directly in the styles file would also simplify it by allowing filters to be applied directly to the styles array. Given that there's integrations that break on unexpected input, these should be fixed before doing such a thing.
- I'd prefer not to add other keys to the styles that aren't used in generation. If the API ignores them, though, it should be fine.
  - Ideally, keys in the styles file would be identical to parameters, allowing an interface to load the file, apply user input on top of it, and submit to Horde. The current format already prevents this, though (sampler and cfg)

**Comment by rbrtcs1** [comment]
You are correct that I missed the existing line art style (and i just tested it out and it seems good).

I really like the idea of adding tags for horde/community/lora/prompt/etc. Although as the number of tags increases it would be important to ensure similar ones get merged together (i.e. you likely wouldn't want both "photo" and "photography" tags).

You may want to continue with this push toward loras, but I have had a lot of success writing prompt styles with prompts-only (even very simple ones like the caricature style work surprisingly well with albedoxl - although I'm sure there's room for improvement).

**Comment by db0** [comment]
OK @Efreak use your best judgement here. if you think the styles are good enough it's OK. I just think that it their value is in easily adding things a layman wouldn't think of when trying to do that style.

Likewise feel free to prune obsolete styles. 

I'll leave the merge to you.

**Pull request merged**
